# Generated by Django 5.1.7 on 2025-04-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
